source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Keyboardy_Example', :exclusive => true do
  pod "Keyboardy", :path => "../"
end

target 'Keyboardy_Tests', :exclusive => true do
  pod "Keyboardy", :path => "../"

  
end
