source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.3'

target 'Keyboardy_Example' do
  pod "Keyboardy", :path => "../"
end

target 'Keyboardy_Tests' do
  pod "Keyboardy", :path => "../"
end
